<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE wbxml [
  <!ELEMENT wbxml (PublicIdentifiers,App+)>
  <!ATTLIST wbxml version NMTOKEN #REQUIRED>
  <!ELEMENT PublicIdentifiers (PublicIdentifier)*>
  <!ELEMENT PublicIdentifier EMPTY>
  <!ATTLIST PublicIdentifier value NMTOKEN #REQUIRED>
  <!ATTLIST PublicIdentifier name CDATA #REQUIRED>
  <!ELEMENT App (TagTokens?,AttrStartTokens?,AttrValueTokens?,Ext0Values?,Ext1Values?,Ext2Values?,CharacterEntities?)>
  <!ATTLIST App publicid CDATA #REQUIRED>
  <!ATTLIST App systemid CDATA #IMPLIED>
  <!ATTLIST App use-default (no|yes) #IMPLIED>
  <!ATTLIST App variable-subs (no|yes) #IMPLIED>	<!-- WAP / WML -->
  <!ATTLIST App textual-ext NMTOKEN #IMPLIED>
  <!ATTLIST App tokenised-ext NMTOKEN #IMPLIED>
  <!ATTLIST App xml-space (default|preserve) #IMPLIED>
  <!ELEMENT TagTokens (TAG)*>
  <!ELEMENT TAG EMPTY>
  <!ATTLIST TAG token NMTOKEN #REQUIRED>
  <!ATTLIST TAG name NMTOKEN #REQUIRED>
  <!ATTLIST TAG codepage NMTOKEN #IMPLIED>
  <!ATTLIST TAG encoding (base64|datetime|integer) #IMPLIED>	<!-- WV -->
  <!ELEMENT AttrStartTokens (ATTRSTART)*>
  <!ELEMENT ATTRSTART EMPTY>
  <!ATTLIST ATTRSTART token NMTOKEN #REQUIRED>
  <!ATTLIST ATTRSTART name NMTOKEN #REQUIRED>
  <!ATTLIST ATTRSTART value CDATA #IMPLIED>
  <!ATTLIST ATTRSTART codepage NMTOKEN #IMPLIED>
  <!ATTLIST ATTRSTART default CDATA #IMPLIED>
  <!ATTLIST ATTRSTART fixed CDATA #IMPLIED>
  <!ATTLIST ATTRSTART validate (std|length|vdata) #IMPLIED>	<!-- WAP / WML -->
  <!ATTLIST ATTRSTART encoding (std|iso-8601) #IMPLIED>		<!-- WAP -->
  <!ELEMENT AttrValueTokens (ATTRVALUE)*>
  <!ELEMENT ATTRVALUE EMPTY>
  <!ATTLIST ATTRVALUE token NMTOKEN #REQUIRED>
  <!ATTLIST ATTRVALUE value CDATA #REQUIRED>
  <!ATTLIST ATTRVALUE codepage NMTOKEN #IMPLIED>
  <!ELEMENT Ext0Values (EXTVALUE)*>	<!-- WV -->
  <!ELEMENT Ext1Values (EXTVALUE)*>
  <!ELEMENT Ext2Values (EXTVALUE)*>
  <!ELEMENT EXTVALUE EMPTY>
  <!ATTLIST EXTVALUE index NMTOKEN #REQUIRED>
  <!ATTLIST EXTVALUE value CDATA #REQUIRED>
  <!ELEMENT CharacterEntities (CharacterEntity)*>
  <!ELEMENT CharacterEntity EMPTY>
  <!ATTLIST CharacterEntity name NMTOKEN #REQUIRED>
  <!ATTLIST CharacterEntity code NMTOKEN #REQUIRED>
  <!ENTITY quot "&#34;">
  <!ENTITY amp "&#38;#38;">
  <!ENTITY apos "&#39;">
  <!ENTITY lt "&#38;#60;">
  <!ENTITY gt ">">
]>
<wbxml version="1.3">
  <!--  see: Binary XML Content Format, Version 1.3 -->
  <!--       WAP-192-WBXML-20010725-a -->
  <PublicIdentifiers>
    <!-- The normative list of well known public identifiers issued, and maintained,
         by the OMNA (Open Mobile Naming Authority) SHALL be found
         at http://www.openmobilealliance.org/tech/omna/omna-wbxml-public-docid.htm -->
    <!-- value="1"  Unknown or missing public identifier
         if no value, publicid is encoding as string -->
    <PublicIdentifier value="2"  name="-//WAPFORUM//DTD WML 1.0//EN"/>
    <!--   DEPRECATED       value="3"  name="-//WAPFORUM//DTD WTA 1.0//EN" -->
    <PublicIdentifier value="4"  name="-//WAPFORUM//DTD WML 1.1//EN"/>
    <PublicIdentifier value="5"  name="-//WAPFORUM//DTD SI 1.0//EN"/>
    <PublicIdentifier value="6"  name="-//WAPFORUM//DTD SL 1.0//EN"/>
    <PublicIdentifier value="7"  name="-//WAPFORUM//DTD CO 1.0//EN"/>
    <PublicIdentifier value="8"  name="-//WAPFORUM//DTD CHANNEL 1.1//EN"/>
    <PublicIdentifier value="9"  name="-//WAPFORUM//DTD WML 1.2//EN"/>
    <PublicIdentifier value="A"  name="-//WAPFORUM//DTD WML 1.3//EN"/>
    <PublicIdentifier value="B"  name="-//WAPFORUM//DTD PROV 1.0//EN"/>
    <PublicIdentifier value="C"  name="-//WAPFORUM//DTD WTA-WML 1.2//EN"/>
    <PublicIdentifier value="D"  name="-//WAPFORUM//DTD EMN 1.0//EN"/>
    <PublicIdentifier value="E"  name="-//OMA//DTD DRMREL 1.0//EN"/>
    <PublicIdentifier value="F"  name="-//WIRELESSVILLAGE//DTD CSP 1.0//EN"/>
    <PublicIdentifier value="10" name="-//WIRELESSVILLAGE//DTD CSP 1.1//EN"/>
    <PublicIdentifier value="11" name="-//OMA//DTD WV-CSP 1.2//EN"/>
    <!-- values 12-7F : Reserved -->
    <PublicIdentifier value="1201" name="-//SYNCML//DTD SyncML 1.2//EN"/>
    <PublicIdentifier value="1202" name="-//SYNCML//DTD MetaInf 1.2//EN"/>
    <PublicIdentifier value="1203" name="-//SYNCML//DTD DevInf 1.2//EN"/>
  </PublicIdentifiers>
  <App publicid="-//WAPFORUM//DTD SI 1.0//EN" use-default="yes" textual-ext="si" tokenised-ext="sic" xml-space="default"
       systemid="http://www.wapforum.org/DTD/si.dtd">
    <!-- see: Service Indication, WAP-167-ServiceInd-20010731-a -->
    <TagTokens>
      <TAG token="05" name="si"/>
      <TAG token="06" name="indication"/>
      <TAG token="07" name="info"/>
      <TAG token="08" name="item"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="action" value="signal-none"/>
      <ATTRSTART token="06" name="action" value="signal-low"/>
      <ATTRSTART token="07" name="action" value="signal-medium" default="indication"/>
      <ATTRSTART token="08" name="action" value="signal-high"/>
      <ATTRSTART token="09" name="action" value="delete"/>
      <ATTRSTART token="0A" name="created" encoding="iso-8601"/>
      <ATTRSTART token="0B" name="href"/>
      <ATTRSTART token="0C" name="href" value="http://"/>
      <ATTRSTART token="0D" name="href" value="http://www."/>
      <ATTRSTART token="0E" name="href" value="https://"/>
      <ATTRSTART token="0F" name="href" value="https://www."/>
      <ATTRSTART token="10" name="si-expires" encoding="iso-8601"/>
      <ATTRSTART token="11" name="si-id"/>
      <ATTRSTART token="12" name="class"/>
    </AttrStartTokens>
    <AttrValueTokens>
      <ATTRVALUE token="85" value=".com/"/>
      <ATTRVALUE token="86" value=".edu/"/>
      <ATTRVALUE token="87" value=".net/"/>
      <ATTRVALUE token="88" value=".org/"/>
    </AttrValueTokens>
  </App>
  <App publicid="-//WAPFORUM//DTD SL 1.0//EN" use-default="yes" textual-ext="sl" tokenised-ext="slc" xml-space="default"
       systemid="http://www.wapforum.org/DTD/sl.dtd">
    <!-- see: Service Loading, WAP-168-ServiceLoad-20010731-a -->
    <TagTokens>
      <TAG token="05" name="sl"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="action" value="execute-low" default="sl"/>
      <ATTRSTART token="06" name="action" value="execute-high"/>
      <ATTRSTART token="07" name="action" value="cache"/>
      <ATTRSTART token="08" name="href"/>
      <ATTRSTART token="09" name="href" value="http://"/>
      <ATTRSTART token="0A" name="href" value="http://www."/>
      <ATTRSTART token="0B" name="href" value="https://"/>
      <ATTRSTART token="0C" name="href" value="https://www."/>
    </AttrStartTokens>
    <AttrValueTokens>
      <ATTRVALUE token="85" value=".com/"/>
      <ATTRVALUE token="86" value=".edu/"/>
      <ATTRVALUE token="87" value=".net/"/>
      <ATTRVALUE token="88" value=".org/"/>
    </AttrValueTokens>
  </App>
  <App publicid="-//WAPFORUM//DTD CO 1.0//EN" textual-ext="co" tokenised-ext="coc" xml-space="default"
       systemid="http://www.wapforom.org/DTD/co_1.0.dtd">
    <!-- see: Cache Operation, WAP-175-CacheOp-20010731-a -->
    <TagTokens>
      <TAG token="05" name="co"/>
      <TAG token="06" name="invalidate-object"/>
      <TAG token="07" name="invalidate-service"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="uri"/>
      <ATTRSTART token="06" name="uri" value="http://"/>
      <ATTRSTART token="07" name="uri" value="http://www."/>
      <ATTRSTART token="08" name="uri" value="https://"/>
      <ATTRSTART token="09" name="uri" value="https://www."/>
    </AttrStartTokens>
    <AttrValueTokens>
      <ATTRVALUE token="85" value=".com/"/>
      <ATTRVALUE token="86" value=".edu/"/>
      <ATTRVALUE token="87" value=".net/"/>
      <ATTRVALUE token="88" value=".org/"/>
    </AttrValueTokens>
  </App>
  <App publicid="-//WAPFORUM//DTD CHANNEL 1.2//EN" textual-ext="channel" tokenised-ext="channelc" xml-space="default"
       systemid="channel.dtd">
    <!-- see: WAP Wireless Telephony Application -->
    <!--      WAP-266-WTA-20010711-p -->
    <TagTokens>
      <TAG token="05" name="channel"/>
      <TAG token="06" name="title"/>
      <TAG token="07" name="abstract"/>
      <TAG token="08" name="resource"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="maxspace"/>
      <ATTRSTART token="06" name="base"/>
      <ATTRSTART token="07" name="href"/>
      <ATTRSTART token="08" name="href" value="http://"/>
      <ATTRSTART token="09" name="href" value="https://"/>
      <ATTRSTART token="0A" name="lastmod"/>
      <ATTRSTART token="0B" name="etag"/>
      <ATTRSTART token="0C" name="md5"/>
      <ATTRSTART token="0D" name="success"/>
      <ATTRSTART token="0E" name="success" value="http://"/>
      <ATTRSTART token="0F" name="success" value="https://"/>
      <ATTRSTART token="10" name="failure"/>
      <ATTRSTART token="11" name="failure" value="http://"/>
      <ATTRSTART token="12" name="failure" value="https://"/>
      <ATTRSTART token="13" name="eventid"/>
      <ATTRSTART token="14" name="eventid" value="wtaev-"/>
      <ATTRSTART token="15" name="channelid"/>
      <ATTRSTART token="16" name="useraccessible"/>
    </AttrStartTokens>
  </App>
  <App publicid="-//WAPFORUM//DTD CHANNEL 1.1//EN" textual-ext="channel" tokenised-ext="channelc" xml-space="default"
       systemid="channel.dtd">
    <!-- see: WAP WTA, Version 08-Nov-1999 -->
    <TagTokens>
      <TAG token="05" name="channel"/>
      <TAG token="06" name="title"/>
      <TAG token="07" name="abstract"/>
      <TAG token="08" name="resource"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="maxspace"/>
      <ATTRSTART token="06" name="base"/>
      <ATTRSTART token="07" name="href"/>
      <ATTRSTART token="08" name="href" value="http://"/>
      <ATTRSTART token="09" name="href" value="https://"/>
      <ATTRSTART token="0A" name="lastmod"/>
      <ATTRSTART token="0B" name="etag"/>
      <ATTRSTART token="0C" name="md5"/>
      <ATTRSTART token="0D" name="success"/>
      <ATTRSTART token="0E" name="success" value="http://"/>
      <ATTRSTART token="0F" name="success" value="https://"/>
      <ATTRSTART token="10" name="failure"/>
      <ATTRSTART token="11" name="failure" value="http://"/>
      <ATTRSTART token="12" name="failure" value="https://"/>
      <ATTRSTART token="13" name="EventId"/>
    </AttrStartTokens>
  </App>
  <App publicid="-//WAPFORUM//DTD WML 1.3//EN" use-default="yes" variable-subs="yes" textual-ext="wml" tokenised-ext="wmlc" xml-space="default"
       systemid="http://www.wapforum.org/DTD/wml13.dtd">
    <!-- see: WAP WML, Version 19-Feb-2000 -->
    <!--      Wireless Markup Language Specification, Version 1.3 -->
    <TagTokens>
      <TAG token="1C" name="a"/>
      <TAG token="22" name="anchor"/>
      <TAG token="23" name="access"/>
      <TAG token="24" name="b"/>
      <TAG token="25" name="big"/>
      <TAG token="26" name="br"/>
      <TAG token="27" name="card"/>
      <TAG token="28" name="do"/>
      <TAG token="29" name="em"/>
      <TAG token="2A" name="fielset"/>
      <TAG token="2B" name="go"/>
      <TAG token="2C" name="head"/>
      <TAG token="2D" name="i"/>
      <TAG token="2E" name="img"/>
      <TAG token="2F" name="input"/>
      <TAG token="30" name="meta"/>
      <TAG token="31" name="noop"/>
      <TAG token="20" name="p"/>
      <TAG token="21" name="postfield"/>
      <TAG token="1B" name="pre"/>
      <TAG token="32" name="prev"/>
      <TAG token="33" name="onevent"/>
      <TAG token="34" name="optgroup"/>
      <TAG token="35" name="option"/>
      <TAG token="36" name="refresh"/>
      <TAG token="37" name="select"/>
      <TAG token="3E" name="setvar"/>
      <TAG token="38" name="small"/>
      <TAG token="39" name="strong"/>
      <TAG token="1F" name="table"/>
      <TAG token="1D" name="td"/>
      <TAG token="3B" name="template"/>
      <TAG token="3C" name="timer"/>
      <TAG token="1E" name="tr"/>
      <TAG token="3D" name="u"/>
      <TAG token="3F" name="wml"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="accept-charset"/>
      <ATTRSTART token="5E" name="accesskey" validate="vdata"/>
      <ATTRSTART token="52" name="align"/>
      <ATTRSTART token="06" name="align" value="bottom" default="img"/>
      <ATTRSTART token="07" name="align" value="center"/>
      <ATTRSTART token="08" name="align" value="left" default="p"/>
      <ATTRSTART token="09" name="align" value="middle"/>
      <ATTRSTART token="0A" name="align" value="right"/>
      <ATTRSTART token="0B" name="align" value="top"/>
      <ATTRSTART token="0C" name="alt" validate="vdata"/>
      <ATTRSTART token="64" name="cache-control" value="no-cache"/>
      <ATTRSTART token="54" name="class"/>
      <ATTRSTART token="53" name="columns"/>
      <ATTRSTART token="0D" name="content"/>
      <ATTRSTART token="5C" name="content" value="application/vnd.wap.wmlc;charset="/>
      <ATTRSTART token="0F" name="domain"/>
      <ATTRSTART token="10" name="emptyok" value="false" default="input"/>
      <ATTRSTART token="11" name="emptyok" value="true"/>
      <ATTRSTART token="5F" name="enctype" validate="vdata"/>
      <ATTRSTART token="60" name="enctype" value="application/x-www-form-urlencoded" default="go" validate="vdata"/>
      <ATTRSTART token="61" name="enctype" value="multipart/form-data" validate="vdata"/>
      <ATTRSTART token="12" name="format"/>
      <ATTRSTART token="56" name="forua" value="false" default="meta"/>
      <ATTRSTART token="57" name="forua" value="true"/>
      <ATTRSTART token="13" name="height" validate="length"/>
      <ATTRSTART token="4A" name="href" validate="vdata"/>
      <ATTRSTART token="4B" name="href" value="http://" validate="vdata"/>
      <ATTRSTART token="4C" name="href" value="https://" validate="vdata"/>
      <ATTRSTART token="14" name="hspace" validate="length" default="0"/>
      <ATTRSTART token="5A" name="http-equiv"/>
      <ATTRSTART token="5B" name="http-equiv" value="Content-Type"/>
      <ATTRSTART token="5D" name="http-equiv" value="Expires"/>
      <ATTRSTART token="55" name="id"/>
      <ATTRSTART token="15" name="ivalue" validate="vdata"/>
      <ATTRSTART token="16" name="iname"/>
      <ATTRSTART token="18" name="label" validate="vdata"/>
      <ATTRSTART token="19" name="localsrc" validate="vdata"/>
      <ATTRSTART token="1A" name="maxlength"/>
      <ATTRSTART token="1B" name="method" value="get" default="go"/>
      <ATTRSTART token="1C" name="method" value="post"/>
      <ATTRSTART token="1D" name="mode" value="nowrap"/>
      <ATTRSTART token="1E" name="mode" value="wrap"/>
      <ATTRSTART token="1F" name="multiple" value="false" default="select"/>
      <ATTRSTART token="20" name="multiple" value="true"/>
      <ATTRSTART token="21" name="name" validate="vdata"/>
      <ATTRSTART token="22" name="newcontext" value="false" default="card"/>
      <ATTRSTART token="23" name="newcontext" value="true"/>
      <ATTRSTART token="25" name="onenterbackward" validate="vdata"/>
      <ATTRSTART token="26" name="onenterforward" validate="vdata"/>
      <ATTRSTART token="24" name="onpick" validate="vdata"/>
      <ATTRSTART token="27" name="ontimer" validate="vdata"/>
      <ATTRSTART token="28" name="optional" value="false" default="do"/>
      <ATTRSTART token="29" name="optional" value="true"/>
      <ATTRSTART token="2A" name="path"/>
      <ATTRSTART token="2E" name="scheme"/>
      <ATTRSTART token="2F" name="sendreferer" value="false" default="go"/>
      <ATTRSTART token="30" name="sendreferer" value="true"/>
      <ATTRSTART token="31" name="size"/>
      <ATTRSTART token="32" name="src" validate="vdata"/>
      <ATTRSTART token="58" name="src" value="http://" validate="vdata"/>
      <ATTRSTART token="59" name="src" value="https://" validate="vdata"/>
      <ATTRSTART token="33" name="ordered" value="true" default="card"/>
      <ATTRSTART token="34" name="ordered" value="false"/>
      <ATTRSTART token="35" name="tabindex"/>
      <ATTRSTART token="36" name="title" validate="vdata"/>
      <ATTRSTART token="37" name="type"/>
      <ATTRSTART token="38" name="type" value="accept"/>
      <ATTRSTART token="39" name="type" value="delete"/>
      <ATTRSTART token="3A" name="type" value="help"/>
      <ATTRSTART token="3B" name="type" value="password"/>
      <ATTRSTART token="3C" name="type" value="onpick"/>
      <ATTRSTART token="3D" name="type" value="onenterbackward"/>
      <ATTRSTART token="3E" name="type" value="onenterforward"/>
      <ATTRSTART token="3F" name="type" value="ontimer"/>
      <ATTRSTART token="45" name="type" value="options"/>
      <ATTRSTART token="46" name="type" value="prev"/>
      <ATTRSTART token="47" name="type" value="reset"/>
      <ATTRSTART token="48" name="type" value="text" default="input"/>
      <ATTRSTART token="49" name="type" value="vnd."/>
      <ATTRSTART token="4D" name="value" validate="vdata"/>
      <ATTRSTART token="4E" name="vspace" validate="length" default="0"/>
      <ATTRSTART token="4F" name="width" validate="length"/>
      <ATTRSTART token="50" name="xml:lang"/>
      <ATTRSTART token="62" name="xml:space" value="preserve" fixed="pre"/>
      <ATTRSTART token="63" name="xml:space" value="default"/>
    </AttrStartTokens>
    <AttrValueTokens>
      <ATTRVALUE token="85" value=".com/"/>
      <ATTRVALUE token="86" value=".edu/"/>
      <ATTRVALUE token="87" value=".net/"/>
      <ATTRVALUE token="88" value=".org/"/>
      <ATTRVALUE token="89" value="accept"/>
      <ATTRVALUE token="8A" value="bottom"/>
      <ATTRVALUE token="8B" value="clear"/>
      <ATTRVALUE token="8C" value="delete"/>
      <ATTRVALUE token="8D" value="help"/>
      <ATTRVALUE token="8E" value="http://"/>
      <ATTRVALUE token="8F" value="http://www."/>
      <ATTRVALUE token="90" value="https://"/>
      <ATTRVALUE token="91" value="https://www."/>
      <ATTRVALUE token="93" value="middle"/>
      <ATTRVALUE token="94" value="nowrap"/>
      <ATTRVALUE token="96" value="onenterbackward"/>
      <ATTRVALUE token="97" value="onenterforward"/>
      <ATTRVALUE token="95" value="onpick"/>
      <ATTRVALUE token="98" value="ontimer"/>
      <ATTRVALUE token="99" value="options"/>
      <ATTRVALUE token="9A" value="password"/>
      <ATTRVALUE token="9B" value="reset"/>
      <ATTRVALUE token="9D" value="text"/>
      <ATTRVALUE token="9E" value="top"/>
      <ATTRVALUE token="9F" value="unknown"/>
      <ATTRVALUE token="A0" value="wrap"/>
      <ATTRVALUE token="A1" value="www."/>
    </AttrValueTokens>
    <CharacterEntities>
      <CharacterEntity code="160" name="nbsp"/>
      <CharacterEntity code="173" name="shy"/>
    </CharacterEntities>
  </App>
  <App publicid="-//WAPFORUM//DTD WML 1.2//EN" use-default="yes" variable-subs="yes" textual-ext="wml" tokenised-ext="wmlc" xml-space="default"
       systemid="http://www.wapforum.org/DTD/wml12.dtd">
    <!-- see: WAP WML, Version 04-Nov-1999 -->
    <!--      Wireless Markup Language Specification, Version 1.2 -->
    <TagTokens>
      <TAG token="1C" name="a"/>
      <TAG token="22" name="anchor"/>
      <TAG token="23" name="access"/>
      <TAG token="24" name="b"/>
      <TAG token="25" name="big"/>
      <TAG token="26" name="br"/>
      <TAG token="27" name="card"/>
      <TAG token="28" name="do"/>
      <TAG token="29" name="em"/>
      <TAG token="2A" name="fielset"/>
      <TAG token="2B" name="go"/>
      <TAG token="2C" name="head"/>
      <TAG token="2D" name="i"/>
      <TAG token="2E" name="img"/>
      <TAG token="2F" name="input"/>
      <TAG token="30" name="meta"/>
      <TAG token="31" name="noop"/>
      <TAG token="20" name="p"/>
      <TAG token="21" name="postfield"/>
      <TAG token="1B" name="pre"/>
      <TAG token="32" name="prev"/>
      <TAG token="33" name="onevent"/>
      <TAG token="34" name="optgroup"/>
      <TAG token="35" name="option"/>
      <TAG token="36" name="refresh"/>
      <TAG token="37" name="select"/>
      <TAG token="3E" name="setvar"/>
      <TAG token="38" name="small"/>
      <TAG token="39" name="strong"/>
      <TAG token="1F" name="table"/>
      <TAG token="1D" name="td"/>
      <TAG token="3B" name="template"/>
      <TAG token="3C" name="timer"/>
      <TAG token="1E" name="tr"/>
      <TAG token="3D" name="u"/>
      <TAG token="3F" name="wml"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="accept-charset"/>
      <ATTRSTART token="5E" name="accesskey" validate="vdata"/>
      <ATTRSTART token="52" name="align"/>
      <ATTRSTART token="06" name="align" value="bottom" default="img"/>
      <ATTRSTART token="07" name="align" value="center"/>
      <ATTRSTART token="08" name="align" value="left" default="p"/>
      <ATTRSTART token="09" name="align" value="middle"/>
      <ATTRSTART token="0A" name="align" value="right"/>
      <ATTRSTART token="0B" name="align" value="top"/>
      <ATTRSTART token="0C" name="alt" validate="vdata"/>
      <ATTRSTART token="54" name="class"/>
      <ATTRSTART token="53" name="columns"/>
      <ATTRSTART token="0D" name="content"/>
      <ATTRSTART token="5C" name="content" value="application/vnd.wap.wmlc;charset="/>
      <ATTRSTART token="0F" name="domain"/>
      <ATTRSTART token="10" name="emptyok" value="false" default="input"/>
      <ATTRSTART token="11" name="emptyok" value="true"/>
      <ATTRSTART token="5F" name="enctype" validate="vdata"/>
      <ATTRSTART token="60" name="enctype" value="application/x-www-form-urlencoded" default="go" validate="vdata"/>
      <ATTRSTART token="61" name="enctype" value="multipart/form-data" validate="vdata"/>
      <ATTRSTART token="12" name="format"/>
      <ATTRSTART token="56" name="forua" value="false" default="meta"/>
      <ATTRSTART token="57" name="forua" value="true"/>
      <ATTRSTART token="13" name="height" validate="length"/>
      <ATTRSTART token="4A" name="href" validate="vdata"/>
      <ATTRSTART token="4B" name="href" value="http://" validate="vdata"/>
      <ATTRSTART token="4C" name="href" value="https://" validate="vdata"/>
      <ATTRSTART token="14" name="hspace" validate="length" default="0"/>
      <ATTRSTART token="5A" name="http-equiv"/>
      <ATTRSTART token="5B" name="http-equiv" value="Content-Type"/>
      <ATTRSTART token="5D" name="http-equiv" value="Expires"/>
      <ATTRSTART token="55" name="id"/>
      <ATTRSTART token="15" name="ivalue" validate="vdata"/>
      <ATTRSTART token="16" name="iname"/>
      <ATTRSTART token="18" name="label" validate="vdata"/>
      <ATTRSTART token="19" name="localsrc" validate="vdata"/>
      <ATTRSTART token="1A" name="maxlength"/>
      <ATTRSTART token="1B" name="method" value="get" default="go"/>
      <ATTRSTART token="1C" name="method" value="post"/>
      <ATTRSTART token="1D" name="mode" value="nowrap"/>
      <ATTRSTART token="1E" name="mode" value="wrap"/>
      <ATTRSTART token="1F" name="multiple" value="false" default="select"/>
      <ATTRSTART token="20" name="multiple" value="true"/>
      <ATTRSTART token="21" name="name" validate="vdata"/>
      <ATTRSTART token="22" name="newcontext" value="false" default="card"/>
      <ATTRSTART token="23" name="newcontext" value="true"/>
      <ATTRSTART token="25" name="onenterbackward" validate="vdata"/>
      <ATTRSTART token="26" name="onenterforward" validate="vdata"/>
      <ATTRSTART token="24" name="onpick" validate="vdata"/>
      <ATTRSTART token="27" name="ontimer" validate="vdata"/>
      <ATTRSTART token="28" name="optional" value="false" default="do"/>
      <ATTRSTART token="29" name="optional" value="true"/>
      <ATTRSTART token="2A" name="path"/>
      <ATTRSTART token="2E" name="scheme"/>
      <ATTRSTART token="2F" name="sendreferer" value="false" default="go"/>
      <ATTRSTART token="30" name="sendreferer" value="true"/>
      <ATTRSTART token="31" name="size"/>
      <ATTRSTART token="32" name="src" validate="vdata"/>
      <ATTRSTART token="58" name="src" value="http://" validate="vdata"/>
      <ATTRSTART token="59" name="src" value="https://" validate="vdata"/>
      <ATTRSTART token="33" name="ordered" value="true" default="card"/>
      <ATTRSTART token="34" name="ordered" value="false"/>
      <ATTRSTART token="35" name="tabindex"/>
      <ATTRSTART token="36" name="title" validate="vdata"/>
      <ATTRSTART token="37" name="type"/>
      <ATTRSTART token="38" name="type" value="accept"/>
      <ATTRSTART token="39" name="type" value="delete"/>
      <ATTRSTART token="3A" name="type" value="help"/>
      <ATTRSTART token="3B" name="type" value="password"/>
      <ATTRSTART token="3C" name="type" value="onpick"/>
      <ATTRSTART token="3D" name="type" value="onenterbackward"/>
      <ATTRSTART token="3E" name="type" value="onenterforward"/>
      <ATTRSTART token="3F" name="type" value="ontimer"/>
      <ATTRSTART token="45" name="type" value="options"/>
      <ATTRSTART token="46" name="type" value="prev"/>
      <ATTRSTART token="47" name="type" value="reset"/>
      <ATTRSTART token="48" name="type" value="text" default="input"/>
      <ATTRSTART token="49" name="type" value="vnd."/>
      <ATTRSTART token="4D" name="value" validate="vdata"/>
      <ATTRSTART token="4E" name="vspace" validate="length" default="0"/>
      <ATTRSTART token="4F" name="width" validate="length"/>
      <ATTRSTART token="50" name="xml:lang"/>
      <ATTRSTART token="00" name="xml:space" value="preserve" fixed="pre"/>
    </AttrStartTokens>
    <AttrValueTokens>
      <ATTRVALUE token="85" value=".com/"/>
      <ATTRVALUE token="86" value=".edu/"/>
      <ATTRVALUE token="87" value=".net/"/>
      <ATTRVALUE token="88" value=".org/"/>
      <ATTRVALUE token="89" value="accept"/>
      <ATTRVALUE token="8A" value="bottom"/>
      <ATTRVALUE token="8B" value="clear"/>
      <ATTRVALUE token="8C" value="delete"/>
      <ATTRVALUE token="8D" value="help"/>
      <ATTRVALUE token="8E" value="http://"/>
      <ATTRVALUE token="8F" value="http://www."/>
      <ATTRVALUE token="90" value="https://"/>
      <ATTRVALUE token="91" value="https://www."/>
      <ATTRVALUE token="93" value="middle"/>
      <ATTRVALUE token="94" value="nowrap"/>
      <ATTRVALUE token="96" value="onenterbackward"/>
      <ATTRVALUE token="97" value="onenterforward"/>
      <ATTRVALUE token="95" value="onpick"/>
      <ATTRVALUE token="98" value="ontimer"/>
      <ATTRVALUE token="99" value="options"/>
      <ATTRVALUE token="9A" value="password"/>
      <ATTRVALUE token="9B" value="reset"/>
      <ATTRVALUE token="9D" value="text"/>
      <ATTRVALUE token="9E" value="top"/>
      <ATTRVALUE token="9F" value="unknown"/>
      <ATTRVALUE token="A0" value="wrap"/>
      <ATTRVALUE token="A1" value="www."/>
    </AttrValueTokens>
    <CharacterEntities>
      <CharacterEntity code="160" name="nbsp"/>
      <CharacterEntity code="173" name="shy"/>
    </CharacterEntities>
  </App>
  <App publicid="-//WAPFORUM//DTD WML 1.1//EN" use-default="yes" variable-subs="yes" textual-ext="wml" tokenised-ext="wmlc" xml-space="default"
       systemid="http://www.wapforum.org/DTD/wml_1.1.xml">
    <!-- see: WAP WML, Version 06-Jun-1999 -->
    <!--      Wireless Markup Language Specification, Version 1.1 -->
    <TagTokens>
      <TAG token="1C" name="a"/>
      <TAG token="22" name="anchor"/>
      <TAG token="23" name="access"/>
      <TAG token="24" name="b"/>
      <TAG token="25" name="big"/>
      <TAG token="26" name="br"/>
      <TAG token="27" name="card"/>
      <TAG token="28" name="do"/>
      <TAG token="29" name="em"/>
      <TAG token="2A" name="fielset"/>
      <TAG token="2B" name="go"/>
      <TAG token="2C" name="head"/>
      <TAG token="2D" name="i"/>
      <TAG token="2E" name="img"/>
      <TAG token="2F" name="input"/>
      <TAG token="30" name="meta"/>
      <TAG token="31" name="noop"/>
      <TAG token="20" name="p"/>
      <TAG token="21" name="postfield"/>
      <TAG token="32" name="prev"/>
      <TAG token="33" name="onevent"/>
      <TAG token="34" name="optgroup"/>
      <TAG token="35" name="option"/>
      <TAG token="36" name="refresh"/>
      <TAG token="37" name="select"/>
      <TAG token="3E" name="setvar"/>
      <TAG token="38" name="small"/>
      <TAG token="39" name="strong"/>
      <TAG token="1F" name="table"/>
      <TAG token="1D" name="td"/>
      <TAG token="3B" name="template"/>
      <TAG token="3C" name="timer"/>
      <TAG token="1E" name="tr"/>
      <TAG token="3D" name="u"/>
      <TAG token="3F" name="wml"/>
    </TagTokens>
    <AttrStartTokens>
      <ATTRSTART token="05" name="accept-charset"/>
      <ATTRSTART token="52" name="align"/>
      <ATTRSTART token="06" name="align" value="bottom" default="img"/>
      <ATTRSTART token="07" name="align" value="center"/>
      <ATTRSTART token="08" name="align" value="left" default="p"/>
      <ATTRSTART token="09" name="align" value="middle"/>
      <ATTRSTART token="0A" name="align" value="right"/>
      <ATTRSTART token="0B" name="align" value="top"/>
      <ATTRSTART token="0C" name="alt" validate="vdata"/>
      <ATTRSTART token="54" name="class"/>
      <ATTRSTART token="53" name="columns"/>
      <ATTRSTART token="0D" name="content"/>
      <ATTRSTART token="5C" name="content" value="application/vnd.wap.wmlc;charset="/>
      <ATTRSTART token="0F" name="domain"/>